Repository Thorfusion/Mekanism-Community-Edition, pull requests merged in 2022-11, with the labels that each got.

#48 Bio-Fuel rework [WIP]
  src/main/java/mekanism/api/MekanismConfig.java
  src/main/java/mekanism/client/nei/ChemicalInjectionChamberRecipeHandler.java
  src/main/java/mekanism/client/render/MekanismRenderer.java
  src/main/java/mekanism/common/Mekanism.java
  src/main/java/mekanism/common/MekanismItems.java
  src/main/java/mekanism/common/tile/TileEntityChemicalInjectionChamber.java
  src/main/java/mekanism/generators/client/gui/GuiBioGenerator.java
  src/main/java/mekanism/generators/client/render/RenderBioGenerator.java
  src/main/java/mekanism/generators/common/GeneratorsCommonProxy.java
  src/main/java/mekanism/generators/common/MekanismGenerators.java
  src/main/java/mekanism/generators/common/inventory/container/ContainerBioGenerator.java
  src/main/java/mekanism/generators/common/tile/TileEntityBioGenerator.java
  src/main/java/mekanism/generators/common/tile/TileEntityGasGenerator.java
  src/main/resources/assets/mekanism/gui/GuiBioGenerator.png
  src/main/resources/assets/mekanism/lang/en_US.lang
  src/main/resources/assets/mekanism/textures/blocks/liquid/LiquidBiomatter.png
  src/main/resources/assets/mekanism/textures/blocks/liquid/LiquidBiomatter.png.mcmeta
  src/main/resources/assets/mekanism/textures/blocks/liquid/LiquidEthanol.png
  src/main/resources/assets/mekanism/textures/blocks/liquid/LiquidEthanol.png.mcmeta
  src/main/resources/assets/mekanism/textures/blocks/liquid/LiquidGlucose.png
  src/main/resources/assets/mekanism/textures/blocks/liquid/LiquidGlucose.png.mcmeta
  src/main/resources/assets/mekanism/textures/items/Yeast.png
Labels: enhancement, in progress

#54 Fix Bio-Generator keep burning biogas even tho its energy is full
  src/main/java/mekanism/generators/common/tile/TileEntityBioGenerator.java
Labels: bug, PRIORITY: HIGH, mustdobeforeupdate, finished

#51 Remove voiceserver, cape module and update downloader
  .github/workflows/gradle.yml
  build.properties
  src/main/java/mekanism/api/MekanismConfig.java
  src/main/java/mekanism/client/ClientConnectionHandler.java
  src/main/java/mekanism/client/ClientProxy.java
  src/main/java/mekanism/client/ClientTickHandler.java
  src/main/java/mekanism/client/MekanismClient.java
  src/main/java/mekanism/client/MekanismKeyHandler.java
  src/main/java/mekanism/client/ThreadClientUpdate.java
  src/main/java/mekanism/client/gui/GuiCredits.java
  src/main/java/mekanism/client/render/item/ItemRenderingHandler.java
  src/main/java/mekanism/client/voice/VoiceClient.java
  src/main/java/mekanism/client/voice/VoiceInput.java
  src/main/java/mekanism/client/voice/VoiceOutput.java
  src/main/java/mekanism/common/CommonProxy.java
  src/main/java/mekanism/common/Mekanism.java
  src/main/java/mekanism/common/MekanismItems.java
  src/main/java/mekanism/common/PacketHandler.java
  src/main/java/mekanism/common/ThreadGetData.java
  src/main/java/mekanism/common/integration/OreDictManager.java
  src/main/java/mekanism/common/item/ItemWalkieTalkie.java
  src/main/java/mekanism/common/network/PacketConfigSync.java
  src/main/java/mekanism/common/network/PacketWalkieTalkieState.java
  src/main/java/mekanism/common/util/MekanismUtils.java
  src/main/java/mekanism/common/voice/VoiceConnection.java
  src/main/java/mekanism/common/voice/VoiceServerManager.java
  src/main/resources/assets/mekanism/textures/items/WalkieTalkieOff.png
  src/main/resources/assets/mekanism/textures/items/WalkieTalkie_ch1.png
  src/main/resources/assets/mekanism/textures/items/WalkieTalkie_ch2.png
  src/main/resources/assets/mekanism/textures/items/WalkieTalkie_ch3.png
  src/main/resources/assets/mekanism/textures/items/WalkieTalkie_ch4.png
  src/main/resources/assets/mekanism/textures/items/WalkieTalkie_ch5.png
  src/main/resources/assets/mekanism/textures/items/WalkieTalkie_ch6.png
  src/main/resources/assets/mekanism/textures/items/WalkieTalkie_ch7.png
  src/main/resources/assets/mekanism/textures/items/WalkieTalkie_ch8.png
  src/main/resources/assets/mekanism/textures/items/WalkieTalkie_ch9.png
Labels: enhancement, PRIORITY: HIGH, mustdobeforeupdate, STATUS: FINISHED

#53 fix fluidtank duplication with fluidstacks Thorfusion#49
  src/main/java/mekanism/common/tile/TileEntityBoilerCasing.java
  src/main/java/mekanism/common/tile/TileEntityDynamicTank.java
  src/main/java/mekanism/common/tile/TileEntityElectricPump.java
  src/main/java/mekanism/common/tile/TileEntityFluidTank.java
  src/main/java/mekanism/common/tile/TileEntityRotaryCondensentrator.java
  src/main/java/mekanism/common/tile/TileEntityThermalEvaporationController.java
Labels: bug, PRIORITY: HIGH, mustdobeforeupdate, STATUS: FINISHED

#57 Fixes #40
  src/main/java/mekanism/generators/common/MekanismGenerators.java
  src/main/java/mekanism/generators/common/tile/turbine/TileEntityTurbineCasing.java
Labels: bug, STATUS: FINISHED, PRIORITY: MED

#58 Move mekanism.txt to this repo
  .github/workflows/gradle.yml
  .gitignore
  Mekanism.txt
  src/main/java/mekanism/common/ThreadGetData.java
Labels: enhancement, PRIORITY: LOW, STATUS: FINISHED
