Repository Thorfusion/Mekanism-Community-Edition, pull requests merged in 2022-12, with the labels that each got.

#61 Restore Walkie Talkie as item
  src/main/java/mekanism/common/MekanismItems.java
  src/main/java/mekanism/common/item/ItemWalkieTalkie.java
  src/main/resources/assets/mekanism/textures/items/WalkieTalkie.png
Labels: enhancement, PRIORITY: MED

#67 add the dump button on factories #39
  src/main/java/mekanism/client/gui/GuiFactory.java
  src/main/java/mekanism/client/gui/GuiMetallurgicInfuser.java
  src/main/resources/assets/mekanism/gui/GuiMetallurgicInfuser.png
  src/main/resources/assets/mekanism/gui/factory/GuiAdvancedFactory.png
  src/main/resources/assets/mekanism/gui/factory/GuiBasicFactory.png
  src/main/resources/assets/mekanism/gui/factory/GuiEliteFactory.png
Labels: enhancement, STATUS: FINISHED, PRIORITY: MED

#69 crash with quantum entangloporter #68
  src/main/java/mekanism/client/gui/GuiQuantumEntangloporter.java
Labels: bug, STATUS: FINISHED, PRIORITY: MED

#65 Add max radius for digitalminer #55
  src/main/java/mekanism/api/MekanismConfig.java
  src/main/java/mekanism/client/gui/GuiDigitalMinerConfig.java
  src/main/java/mekanism/common/CommonProxy.java
  src/main/java/mekanism/common/network/PacketConfigSync.java
  src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
Labels: enhancement, STATUS: FINISHED, PRIORITY: MED

#64 Ic2 compat config
  build.properties
  src/main/java/mekanism/api/MekanismConfig.java
  src/main/java/mekanism/common/CommonProxy.java
  src/main/java/mekanism/common/base/EnergyAcceptorWrapper.java
  src/main/java/mekanism/common/multipart/PartUniversalCable.java
  src/main/java/mekanism/common/network/PacketConfigSync.java
  src/main/java/mekanism/common/tile/TileEntityElectricBlock.java
  src/main/java/mekanism/common/util/CableUtils.java
Labels: enhancement, STATUS: FINISHED, PRIORITY: MED
