Repository Thorfusion/Mekanism-Community-Edition, pull requests merged in 2023-02, with the labels that each got.

#94 Immersive Deuterium
  src/main/java/mekanism/api/MekanismConfig.java
  src/main/java/mekanism/api/gas/GasifyableItems.java
  src/main/java/mekanism/client/gui/GuiElectrolyticSeparator.java
  src/main/java/mekanism/common/CommonProxy.java
  src/main/java/mekanism/common/Mekanism.java
  src/main/java/mekanism/common/inventory/container/ContainerElectrolyticSeparator.java
  src/main/java/mekanism/common/network/PacketConfigSync.java
  src/main/java/mekanism/common/tile/TileEntityChemicalInjectionChamber.java
  src/main/java/mekanism/common/tile/TileEntityElectricPump.java
  src/main/java/mekanism/common/tile/TileEntityElectrolyticSeparator.java
Labels: STATUS: FINISHED, MC: 1.7.10

#95 update to 9.12.3
  README.md
  build.gradle
  gradle.properties
  src/main/java/mekanism/client/gui/GuiMekanismConfig.java
  src/main/java/mekanism/common/CommonProxy.java
  src/main/java/mekanism/common/Mekanism.java
  src/main/java/mekanism/common/config/MEKCEConfig.java
  src/main/java/mekanism/common/config/MekanismConfig.java
  src/main/java/mekanism/common/integration/OreDictManager.java
  src/main/java/mekanism/generators/client/gui/GuiGeneratorsConfig.java
  src/main/java/mekanism/tools/client/gui/GuiToolsConfig.java
  src/main/resources/assets/mekanism/lang/en_us.lang
Labels: MC: 1.12.2

#99 Cleanup
  src/main/java/mekanism/common/inventory/container/ContainerChemicalWasher.java
  src/main/java/mekanism/common/tile/TileEntityChemicalInjectionChamber.java
  src/main/java/mekanism/generators/client/render/RenderBioGenerator.java
Labels: TYPE: BUG, MC: 1.7.10
