Repository Thorfusion/Mekanism-Community-Edition, pull requests merged in 2023-05, with the labels that each got.

#118 Improved Checks on energy items
  src/main/java/mekanism/common/util/ChargeUtils.java
Labels: TYPE: BUG, STATUS: FINISHED, PRIORITY: MED, MC: 1.7.10

#122 #117 bug rendering crash with mariculture infinity water bucket placed in evaporation controller
  src/main/java/mekanism/client/render/tileentity/RenderThermalEvaporationController.java
  src/main/java/mekanism/common/tile/TileEntityFluidicPlenisher.java
  src/main/java/mekanism/common/tile/TileEntityThermalEvaporationController.java
Labels: TYPE: BUG, PRIORITY: HIGH, STATUS: FINISHED, MC: 1.7.10

#121 fix #100 where oredict for platinum didnt apply to dust and below and fix #120
  Mekanism.txt
  gradle.properties
  src/main/java/mekanism/common/Mekanism.java
  src/main/resources/assets/mekanism/lang/zh_CN.lang
Labels: TYPE: BUG, STATUS: FINISHED, PRIORITY: MED, MC: 1.7.10

#125 124 dupe dupe with trapdoors and precision sawmill
  README.md
  gradle.properties
  src/main/java/mekanism/common/Mekanism.java
Labels: TYPE: DUPE, MC: 1.12.2
